<?
if($paidType_ctype=='user'){
 	include("cpages/usertimeline.php");
 	}
if($paidType_ctype=='group'){
 	include("cpages/grouptimeline.php");
 	}
if($paidType_ctype=='page'){
 	include("cpages/pagetimeline.php");
 	}
?> 