<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="bootstrap/dist/css/bootstrap-reboot.css">
	<link rel="stylesheet" type="text/css" href="bootstrap/dist/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="bootstrap/dist/css/bootstrap-grid.css">
    <link rel="stylesheet" type="text/css" href="css/theme-styles.css">
 	<link rel="stylesheet" type="text/css" href="css/blocks.css">
	<link rel="stylesheet" type="text/css" href="css/bootstrap-select.css">
 	<link rel="stylesheet" type="text/css" href="css/daterangepicker.css">
	<link rel="stylesheet" type="text/css" href="css/fonts.css">
	<link rel="stylesheet" type="text/css" href="css/fullcalendar.css">
 	<link rel="stylesheet" type="text/css" href="css/magnific-popup.css">
	<link rel="stylesheet" type="text/css" href="css/mediaelementplayer.css">
	<link rel="stylesheet" type="text/css" href="css/mediaelement-playlist-plugin.min.css">
 	<link rel="stylesheet" type="text/css" href="css/simplecalendar.css">
    <link rel="stylesheet" type="text/css" href="css/jquery.mCustomScrollbar.min.css">
 	<link rel="stylesheet" type="text/css" href="css/swiper.min.css">